<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>false</IsPackable>
    <CheckEolTargetFramework>false</CheckEolTargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ProtectedNumbers.Tests.EndToEnd.Shared\ProtectedNumbers.Tests.EndToEnd.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="ProtectedNumbers.Tests.EndToEnd.Shared"/>
  </ItemGroup>

</Project>
