<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.Testing" />
    <PackageReference Include="ConfirmSteps.Net" />
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="NUnit" />
    <PackageReference Include="NUnit.Analyzers" />
    <PackageReference Include="NUnit3TestAdapter" />
    <PackageReference Include="Shouldly"/>
  </ItemGroup>

  <ItemGroup>
    <Using Include="Aspire.Hosting.ApplicationModel" />
    <Using Include="Aspire.Hosting.Testing" />
    <Using Include="ConfirmSteps" />
    <Using Include="ConfirmSteps.Steps.Http.RequestBuilding" />
    <Using Include="ConfirmSteps.Steps.Http.Rest" />
    <Using Include="Microsoft.Extensions.DependencyInjection" />
    <Using Include="NUnit.Framework" />
    <Using Include="System.Net" />
    <Using Include="Shouldly"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ProtectedNumbers.Tests.EndToEnd.AppHost\ProtectedNumbers.Tests.EndToEnd.AppHost.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="http-client.env.json">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>

</Project>
